# Generated by Django 4.2.9 on 2024-03-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
